version: "3.5"
services:
  erigon:
    image: "erigon.erigon.dnp.dappnode.eth:0.1.8"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v2.56.2
    ports:
      - "30405:30405/tcp"
      - "30405:30405/udp"
    volumes:
      - "data:/home/erigon/.local/share"
    environment:
      P2P_PORT: 30405
      EXTRA_OPTs: "--http.api=engine,eth,erigon,web3,net,debug,trace,txpool"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  data: {}
