version: "3.4"
services:
  erigon:
    image: "erigon.erigon.dnp.dappnode.eth:0.1.0"
    build:
      context: erigon
      args:
        UPSTREAM_VERSION: v2022.01.02
    ports:
      - 30303/tcp
      - 30303/udp
      - 30304/tcp
      - 30304/udp
    restart: unless-stopped
    volumes:
      - "data:/home/erigon/.local/share"
    environment:
      ERIGON_EXTRA_OPTS: ""
  rpcdaemon:
    image: "rpcdaemon.erigon.dnp.dappnode.eth:0.1.0"
    build:
      context: rpcdaemon
      args:
        UPSTREAM_VERSION: v2022.01.02
    pid: "service:erigon"
    environment:
      RPCDAEMON_EXTRA_OPTS: "--http.api=eth,debug,net,web3"
    restart: unless-stopped
    volumes:
      - "data:/home/erigon/.local/share"
volumes:
  data: {}
