version: "3.5"
services:
  erigon:
    image: "erigon.erigon.dnp.dappnode.eth:0.1.8"
    build:
      context: erigon
      args:
        UPSTREAM_VERSION: v2022.08.02
    ports:
      - "30315:30315/tcp"
      - "30315:30315/udp"
    volumes:
      - "data:/home/erigon/.local/share"
    environment:
      P2P_PORT: 30315
      EXTRA_OPTs: "--http.api=engine,eth,erigon,web3,net,debug,trace,txpool"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 16384M
volumes:
  data: {}
